import type { Metadata } from "next";
import "./globals.css";
import CreateSurvey from "./components/CreateSurvey";
import Navbar from "@/app/components/Navbar"
import HomePage from "./components/HomePage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CreateSurvey /> 
        <Navbar /> 
        {children} 
      </body>
    </html>
  );
}
