import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Navbar"
// import CreateTripDialog from "./components/CreateTripDialog";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      {/* <CreateTripDialog /> */}
        <Navbar /> 
        {children} 
      </body>
    </html>
  );
}
